### PR TITLE
Feat: add a type safe `withProvider`

### PR DESCRIPTION
**Pull request by siwei-lu**
I think `withProvider` is important to me, and I hope it is built-in. So I made this.

It supports wrapping several stores at the same time.

BTW, I think you might let those React things as peer dependencies instead of dev dependencies. Because there is no need to install them in `reto`.

### CODE REVIEW

**Comment by siwei-lu** [comment]
The type definitions are only for function components. We'd better create a decorator for class components.

However, I won't use any class component. So I didn't do that.

**Comment by awmleer** [comment]
Thanks for your work!

But their is a problem:

image

Type checking is missing here. It should show an error since the args type of `FooStore` is `[]`.

**Comment by awmleer** [comment]
Maybe it is better to publish a standalone `reto-with-provider` package? Or you can just write this as a utility function in your projects...😵

**Comment by awmleer** [comment]
> BTW, I think you might let those React things as peer dependencies instead of dev dependencies. Because there is no need to install them in `reto`.

`react` and `react-dom` are for testing. Maybe `react-dom` is not needed, but `react` definitely is.

**Comment by awmleer** [comment]
Actually, `with-wrapper` is very easy to use and it is more powerful than you might think.

You can wrap multiple `Provider` at once:

```jsx
export const App = withWrapper(element => (
  <Provider of={FooStore}>
    <Provider of={BarStore}>
      {element}
    </Provider>
  </Provider>
))(props => {
  return (
    <div>app</div>
  )
})
```

And it can dynamically adjust `args` based on the `props` passed from outside:

```jsx
export const App = withWrapper((element, props) => (
  <Provider of={FooStore} args={[props.foo.id]}>
    {element}
  </Provider>
))(props => {
  return (
    <div>app</div>
  )
})
```

**Comment by siwei-lu** [comment]
> Thanks for your work!
> 
> But their is a problem:
> 
> image
> 
> Type checking is missing here. It should show an error since the args type of `FooStore` is `[]`.

I fixed it. Now we have type checking on args. I didn't notice because I rarely use the args option.

**Comment by siwei-lu** [comment]
> Maybe it is better to publish a standalone `reto-with-provider` package? Or you can just write this as a utility function in your projects...😵

In fact, I had written a `withProvider` in my project. And I don't want to write it in other projects any more. 😂

**Comment by awmleer** [comment]
> In fact, I had written a `withProvider` in my project. And I don't want to write it in other projects any more. 😂

How about publish it as a new npm package? I have discussed with my colleagues about this few days ago. And we all think that `withProvider` brings more pattern violations than convenience.(That's why we removed it in v0.7!)
Since we are planning to recommend the `withWrapper` pattern, if we also add a `withProvider` api, it may cause a lot of confusion. So I think it is a better choice to publish it as a standalone package for some professional users.

**Comment by siwei-lu** [comment]
Allright. It's up to you.

**Comment by awmleer** [comment]
Anyway, thanks for your contribution!

**Pull request closed without merging**
